FROM node:16.13.0 AS builder

COPY ./client ./client
COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock

RUN yarn install
RUN yarn build

FROM caddy:2.4.6

COPY ./public /usr/public
COPY --from=builder ./dist /usr/dist
COPY ./Caddyfile /etc/caddy/Caddyfile

