FROM node:16.13.0 AS builder

COPY ./client ./client
COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock

RUN yarn install 
RUN yarn build

FROM --platform=linux/amd64 node:16.13.0

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock
COPY ./server/package.json ./server/package.json

RUN yarn install 

COPY --from=builder ./dist/index.html ./dist/index.html
COPY ./server ./server
COPY ./public ./public
COPY ./dist ./dist

EXPOSE 3000

CMD yarn start